ovn_namespace: openshift-ovn-kubernetes
openshift_network_type: "{{ lookup('env', 'OPENSHIFT_NETOWRK_TYPE')|default('OVNKubernetes', true) }}"
openshift_prometheus_retention_period: 15d
persistent_monitoring_enable: false
openshift_prometheus_storage_class: standard
openshift_prometheus_storage_size: 10Gi
openshift_alertmanager_storage_class: standard
openshift_alertmanager_storage_size: 2Gi
openshift_infra_node_selector: 'node-role.kubernetes.io/infra: ""'
thanos_enable: "{{ lookup('env', 'THANOS_ENABLE')|default(false, true) }}"
thanos_receiver_url: "{{ lookup('env', 'THANOS_RECEIVER_URL')|default('', true) }}"
dittybopper_enable: "{{ lookup('env', 'ENABLE_DITTYBOPPER')|default(true, true) }}"
kubeconfig_path: "{{ lookup('env', 'KUBECONFIG_PATH')|default('/home/kni/clusterconfigs/auth/kubeconfig', true) }}"
